version: .{build}
branches:
  only:
  - master

image: Visual Studio 2022

init:
- pwsh: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.d).$env:appveyor_build_number"

build_script:
- pwsh: dotnet restore src/Logazmic/Logazmic.csproj
- pwsh: dotnet publish src/Logazmic/Logazmic.csproj -c Release -r win-x64
- pwsh: squirrel/build-appveyor.ps1

artifacts:
- path: squirrel/Releases/*

skip_tags: true

deploy:
  tag: $(appveyor_build_version)
  release: Logazmic - $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: %GITHUB_TOKEN%
  on:
    branch: master
